name: Spellcheck Action
on: 
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@v0
      name: Spellcheck
      with:
        config_path: .spellcheck.yml # put path to configuration file here
        task_name: Markdown
